"""empty message

Revision ID: 66454a2a3dc1
Revises: 8fe72c28c137
Create Date: 2023-03-02 17:48:28.157786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66454a2a3dc1'
down_revision = '8fe72c28c137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('isbn', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('length', sa.String(length=1000), nullable=True),
    sa.Column('genre', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=5), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('isbn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    # ### end Alembic commands ###
